## Filesystem config - pie
 # Partitions
 ## to do: decommonize as the values are m30s speacific
 BOARD_BOOTIMAGE_PARTITION_SIZE := 57671680
 BOARD_CACHEIMAGE_PARTITION_SIZE := 314572800
 BOARD_DTBIMG_PARTITION_SIZE := 8388608
 BOARD_DTBOIMG_PARTITION_SIZE := 8388608
 BOARD_FLASH_BLOCK_SIZE := 4096
 BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67633152
 BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5033164800
 BOARD_VENDORIMAGE_PARTITION_SIZE := 629145600
 
 BOARD_ROOT_EXTRA_FOLDERS := efs
 
 # File system type
 BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
 BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
 BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
 TARGET_COPY_OUT_PRODUCT := system/product
 TARGET_COPY_OUT_SYSTEM := system
 TARGET_COPY_OUT_VENDOR := vendor
 TARGET_USERIMAGES_USE_F2FS := true